# Generated by Django 3.2.13 on 2022-07-21 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('idCargo', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idCargo')),
                ('Nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Cargo',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('idContrato', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idContrato')),
                ('Tipo', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'Contrato',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('idDepto', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idDepto')),
                ('Nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'Departamento',
            },
        ),
        migrations.CreateModel(
            name='HistorialUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('usuario', models.CharField(max_length=45)),
                ('entidad', models.CharField(max_length=45)),
                ('modulo', models.CharField(max_length=45)),
                ('movimiento', models.CharField(max_length=45)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'HistorialUsuario',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idEmpleado', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idEmpleado')),
                ('fechaNac', models.DateField(blank=True, null=True)),
                ('lugarNac', models.CharField(blank=True, max_length=45, null=True)),
                ('RFC', models.CharField(blank=True, max_length=13, null=True)),
                ('CURP', models.CharField(blank=True, max_length=18, null=True)),
                ('Cel', models.CharField(blank=True, max_length=12, null=True)),
                ('Calle', models.CharField(blank=True, max_length=45, null=True)),
                ('noInt', models.IntegerField(blank=True, null=True)),
                ('noExt', models.IntegerField(blank=True, null=True)),
                ('fk_User', models.IntegerField(blank=True, null=True)),
                ('fk_CP', models.ForeignKey(blank=True, db_column='fk_CP', null=True, on_delete=django.db.models.deletion.CASCADE, to='datosgeograficos.cp', verbose_name='Código Postal')),
            ],
            options={
                'db_table': 'Empleado',
            },
        ),
        migrations.CreateModel(
            name='DatosLaborales',
            fields=[
                ('idDatosLab', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idDatosLab')),
                ('Codigo', models.CharField(max_length=5)),
                ('fechaIng', models.DateField()),
                ('fechaBaja', models.DateField(blank=True, null=True)),
                ('sueldoMensual', models.FloatField(blank=True, null=True)),
                ('Referencia1', models.CharField(blank=True, max_length=200, null=True)),
                ('Referencia2', models.CharField(blank=True, max_length=200, null=True)),
                ('Ubicacion', models.CharField(blank=True, max_length=45, null=True)),
                ('Procedencia', models.CharField(blank=True, max_length=10, null=True)),
                ('Observaciones', models.CharField(blank=True, max_length=250, null=True)),
                ('fk_Cargo', models.ForeignKey(db_column='fk_Cargo', on_delete=django.db.models.deletion.CASCADE, to='usuarios.cargo', verbose_name='Cargo')),
                ('fk_Contrato', models.ForeignKey(db_column='fk_Contrato', on_delete=django.db.models.deletion.CASCADE, to='usuarios.contrato', verbose_name='Contrato')),
                ('fk_Empleado', models.ForeignKey(db_column='fk_Empleado', on_delete=django.db.models.deletion.CASCADE, to='usuarios.empleado', verbose_name='Empleado')),
            ],
            options={
                'db_table': 'DatosLaborales',
            },
        ),
        migrations.AddField(
            model_name='cargo',
            name='fk_Depto',
            field=models.ForeignKey(db_column='fk_Depto', on_delete=django.db.models.deletion.CASCADE, to='usuarios.departamento', verbose_name='Departamento'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=45, unique=True)),
                ('Correo', models.EmailField(max_length=255, unique=True, verbose_name='Correo Electronico')),
                ('Nombre', models.CharField(blank=True, max_length=45, null=True, verbose_name='Nombre')),
                ('Apellidos', models.CharField(blank=True, max_length=90, null=True, verbose_name='Apellidos')),
                ('Genero', models.CharField(blank=True, max_length=1, null=True)),
                ('Rol', models.CharField(max_length=15)),
                ('fechaCreacion', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
